# Generated by Django 2.1.2 on 2018-10-22 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat_collectr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='image',
            field=models.TextField(default='#'),
            preserve_default=False,
        ),
    ]
